# site name
site_name: 地球惑星物理学演習
# copyright
copyright: "&copy; 2025 chibutsu-utokyo"
# navigation
nav:
  - Unix:
    - unix/intro.md
    - unix/kadai1.md
    - unix/kadai2.md
  - Gnuplot:
    - gnuplot/gnuplot_1.md
    - gnuplot/gnuplot_2.md
    - gnuplot/gnuplot_3.md
    - gnuplot/gnuplot_appendix.md
  - LaTeX:
    - LaTeX/chap1.md  # LaTeXの基礎知識
    - LaTeX/chap2.md  # LaTeXの基本(1)
    - LaTeX/chap3.md  # LaTeXの基本(2)
    - LaTeX/chap4.md  # 数式
    - LaTeX/chap5.md  # 画像
    - LaTeX/chap6.md  # 付録
    - LaTeX/chap7.md  # 提出課題
  - Remote Access:
    - RemoteAccess/introduction.md  # イントロダクション
    - RemoteAccess/SSH.md  # SSH
    - RemoteAccess/VPN.md  # VPN
    - RemoteAccess/kadai.md  # 課題
    - RemoteAccess/559servers.md  # 559のサーバー群
    - RemoteAccess/cyberattack.md  # サイバー攻撃
  - Python:
    - python/intro.md
    - python/kadai1.md
    - python/kadai2.md
#theme
theme:
  language: ja
  name: material
  font:
    text: Noto Sans JP
    code: Inconsolata
  palette:
    primary: blue grey
  features:
    - navigation.top
    # - toc.integrate
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/chibutsu-utokyo/chibutsu-utokyo.github.io

repo_url: https://github.com/chibutsu-utokyo/chibutsu-utokyo.github.io
repo_name: chibutsu-utokyo

plugins:
  search:
    lang: 'ja'

extra_javascript:
  - js/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - stylesheets/headline.css

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - pymdownx.details
  - footnotes
  - pymdownx.highlight:
      use_pygments: true
      noclasses: true
      anchor_linenums: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
